<?php

namespace ContainerOFu2wWx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JpsdPlvService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.JpsdPlv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JpsdPlv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'pimcore.admin.storage' => ['privates', 'pimcore.admin.storage', 'getPimcore_Admin_StorageService', true],
            'pimcore.asset.storage' => ['privates', 'pimcore.asset.storage', 'getPimcore_Asset_StorageService', true],
            'pimcore.asset_cache.storage' => ['privates', 'pimcore.asset_cache.storage', 'getPimcore_AssetCache_StorageService', true],
            'pimcore.document_static.storage' => ['privates', 'pimcore.document_static.storage', 'getPimcore_DocumentStatic_StorageService', true],
            'pimcore.recycle_bin.storage' => ['privates', 'pimcore.recycle_bin.storage', 'getPimcore_RecycleBin_StorageService', true],
            'pimcore.thumbnail.storage' => ['privates', 'pimcore.thumbnail.storage', 'getPimcore_Thumbnail_StorageService', true],
            'pimcore.version.storage' => ['privates', 'pimcore.version.storage', 'getPimcore_Version_StorageService', true],
        ], [
            'pimcore.admin.storage' => 'League\\Flysystem\\Filesystem',
            'pimcore.asset.storage' => 'League\\Flysystem\\Filesystem',
            'pimcore.asset_cache.storage' => 'League\\Flysystem\\Filesystem',
            'pimcore.document_static.storage' => 'League\\Flysystem\\Filesystem',
            'pimcore.recycle_bin.storage' => 'League\\Flysystem\\Filesystem',
            'pimcore.thumbnail.storage' => 'League\\Flysystem\\Filesystem',
            'pimcore.version.storage' => 'League\\Flysystem\\Filesystem',
        ]);
    }
}
