<?php

namespace ContainerOFu2wWx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MvOr3SService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.mvOr3_S' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mvOr3_S'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'templateExporter' => ['privates', '.errored..service_locator.mvOr3_S.CustomerManagementFrameworkBundle\\Newsletter\\ProviderHandler\\Mailchimp\\TemplateExporter', NULL, 'Cannot autowire service ".service_locator.mvOr3_S": it references class "CustomerManagementFrameworkBundle\\Newsletter\\ProviderHandler\\Mailchimp\\TemplateExporter" but no such service exists.'],
        ], [
            'templateExporter' => 'CustomerManagementFrameworkBundle\\Newsletter\\ProviderHandler\\Mailchimp\\TemplateExporter',
        ]);
    }
}
