<?php

namespace ContainerOFu2wWx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YY9cfkhService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.YY9cfkh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YY9cfkh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'messageBus' => ['services', 'messenger.default_bus', 'getMessenger_DefaultBusService', true],
        ], [
            'messageBus' => '?',
        ]);
    }
}
