<?php

namespace ContainerOFu2wWx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCmf_EventListener_ActionTriggerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'cmf.event_listener.action_trigger' shared autowired service.
     *
     * @return \CustomerManagementFrameworkBundle\ActionTrigger\EventHandler\DefaultEventHandler
     *
     * @deprecated The "cmf.event_listener.action_trigger" service is deprecated. Use "CustomerManagementFrameworkBundle\ActionTrigger\Queue\QueueInterface" instead
     */
    public static function do($container, $lazyLoad = true)
    {
        trigger_deprecation('', '', 'The "cmf.event_listener.action_trigger" service is deprecated. Use "CustomerManagementFrameworkBundle\\ActionTrigger\\Queue\\QueueInterface" instead');

        $container->services['cmf.event_listener.action_trigger'] = $instance = new \CustomerManagementFrameworkBundle\ActionTrigger\EventHandler\DefaultEventHandler(($container->services['cmf.action_trigger.queue'] ?? $container->load('getCmf_ActionTrigger_QueueService')), ($container->services['Knp\\Component\\Pager\\PaginatorInterface'] ?? $container->getPaginatorInterfaceService()));

        $instance->setLogger(($container->services['monolog.logger.cmf'] ?? $container->load('getMonolog_Logger_CmfService')));

        return $instance;
    }
}
