<?php

namespace ContainerOFu2wWx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDefaultEncryptionServiceService extends App_KernelProdContainer
{
    /*
     * Gets the public 'CustomerManagementFrameworkBundle\Encryption\DefaultEncryptionService' shared autowired service.
     *
     * @return \CustomerManagementFrameworkBundle\Encryption\DefaultEncryptionService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/customer-management-framework-bundle/src/Encryption/EncryptionServiceInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/customer-management-framework-bundle/src/Encryption/DefaultEncryptionService.php';

        return $container->services['CustomerManagementFrameworkBundle\\Encryption\\DefaultEncryptionService'] = new \CustomerManagementFrameworkBundle\Encryption\DefaultEncryptionService('TQwX8zIZ4/k1mbrLh14NmK5dvhnU/4EHLfZn5kMfuEo=');
    }
}
