<?php

namespace ContainerOFu2wWx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDefaultActivityManagerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'CustomerManagementFrameworkBundle\ActivityManager\DefaultActivityManager' shared autowired service.
     *
     * @return \CustomerManagementFrameworkBundle\ActivityManager\DefaultActivityManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/customer-management-framework-bundle/src/ActivityManager/ActivityManagerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/customer-management-framework-bundle/src/ActivityManager/DefaultActivityManager.php';

        return $container->services['CustomerManagementFrameworkBundle\\ActivityManager\\DefaultActivityManager'] = new \CustomerManagementFrameworkBundle\ActivityManager\DefaultActivityManager(($container->services['cmf.activity_store'] ?? $container->getCmf_ActivityStoreService()));
    }
}
