<?php

namespace ContainerOFu2wWx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDocumentValueResolverService extends App_KernelProdContainer
{
    /*
     * Gets the private 'Pimcore\Controller\ArgumentValueResolver\DocumentValueResolver' shared autowired service.
     *
     * @return \Pimcore\Controller\ArgumentValueResolver\DocumentValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Controller/ArgumentValueResolver/DocumentValueResolver.php';

        return $container->privates['Pimcore\\Controller\\ArgumentValueResolver\\DocumentValueResolver'] = new \Pimcore\Controller\ArgumentValueResolver\DocumentValueResolver(($container->services['Pimcore\\Http\\Request\\Resolver\\DocumentResolver'] ?? $container->getDocumentResolverService()));
    }
}
