<?php

namespace ContainerOFu2wWx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDuplicatesIndexInterfaceService extends App_KernelProdContainer
{
    /*
     * Gets the public 'CustomerManagementFrameworkBundle\DuplicatesIndex\DuplicatesIndexInterface' shared autowired service.
     *
     * @return \CustomerManagementFrameworkBundle\DuplicatesIndex\DefaultMariaDbDuplicatesIndex
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/customer-management-framework-bundle/src/DuplicatesIndex/DuplicatesIndexInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/customer-management-framework-bundle/src/DuplicatesIndex/DefaultMariaDbDuplicatesIndex.php';

        return $container->services['CustomerManagementFrameworkBundle\\DuplicatesIndex\\DuplicatesIndexInterface'] = new \CustomerManagementFrameworkBundle\DuplicatesIndex\DefaultMariaDbDuplicatesIndex(($container->services['Knp\\Component\\Pager\\PaginatorInterface'] ?? $container->getPaginatorInterfaceService()), true, $container->parameters['pimcore_customer_management_framework.customer_duplicates_services.duplicates_index.duplicateCheckFields'], $container->parameters['pimcore_customer_management_framework.customer_duplicates_services.duplicates_index.dataTransformers']);
    }
}
