<?php

namespace ContainerOFu2wWx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEditmodeValueResolverService extends App_KernelProdContainer
{
    /*
     * Gets the private 'Pimcore\Controller\ArgumentValueResolver\EditmodeValueResolver' shared autowired service.
     *
     * @return \Pimcore\Controller\ArgumentValueResolver\EditmodeValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/lib/Controller/ArgumentValueResolver/EditmodeValueResolver.php';

        return $container->privates['Pimcore\\Controller\\ArgumentValueResolver\\EditmodeValueResolver'] = new \Pimcore\Controller\ArgumentValueResolver\EditmodeValueResolver(($container->services['Pimcore\\Http\\Request\\Resolver\\EditmodeResolver'] ?? $container->getEditmodeResolverService()));
    }
}
