<?php

namespace ContainerOFu2wWx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFileUploadServiceService extends App_KernelProdContainer
{
    /*
     * Gets the public 'Pimcore\Bundle\DataHubBundle\Service\FileUploadService' shared autowired service.
     *
     * @return \Pimcore\Bundle\DataHubBundle\Service\FileUploadService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/data-hub/src/Service/FileUploadService.php';

        return $container->services['Pimcore\\Bundle\\DataHubBundle\\Service\\FileUploadService'] = new \Pimcore\Bundle\DataHubBundle\Service\FileUploadService();
    }
}
