<?php

namespace ContainerOFu2wWx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPimcoreEcommerce_PaymentManager_Provider_UnzerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'pimcore_ecommerce.payment_manager.provider.unzer' shared autowired service.
     *
     * @return \Pimcore\Bundle\EcommerceFrameworkBundle\PaymentManager\Payment\Unzer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/PaymentManager/V7/Payment/PaymentInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/PaymentManager/Payment/AbstractPayment.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/payment-provider-unzer/src/PaymentManager/Payment/Unzer.php';

        $container->privates['pimcore_ecommerce.payment_manager.provider.unzer'] = $instance = new \Pimcore\Bundle\EcommerceFrameworkBundle\PaymentManager\Payment\Unzer(['publicAccessKey' => 's-pub-2a10GBUCSfOqqtyulwXJub7e8m0EwDbP', 'privateAccessKey' => 's-priv-2a10PcxkejMP6YJwHH1shzvHyOd8PrOt']);

        $instance->setConfigurationKey('unzer');

        return $instance;
    }
}
