<?php

namespace ContainerOFu2wWx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPimcoreEcommerce_OfferToolService extends App_KernelProdContainer
{
    /*
     * Gets the public 'pimcore_ecommerce.offer_tool' shared autowired service.
     *
     * @return \Pimcore\Bundle\EcommerceFrameworkBundle\OfferTool\DefaultService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/OfferTool/ServiceInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/OfferTool/DefaultService.php';

        return $container->services['pimcore_ecommerce.offer_tool'] = new \Pimcore\Bundle\EcommerceFrameworkBundle\OfferTool\DefaultService('Pimcore\\Model\\DataObject\\OfferToolOffer', 'Pimcore\\Model\\DataObject\\OfferToolOfferItem', '/offertool/offers/%Y/%m');
    }
}
