<?php

namespace ContainerOFu2wWx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPimcoreEcommerce_CheckoutManager_Default_CommitOrderProcessorService extends App_KernelProdContainer
{
    /*
     * Gets the private 'pimcore_ecommerce.checkout_manager.default.commit_order_processor' shared autowired service.
     *
     * @return \Pimcore\Bundle\EcommerceFrameworkBundle\CheckoutManager\V7\CommitOrderProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/CheckoutManager/CommitOrderProcessorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/pimcore/bundles/EcommerceFrameworkBundle/CheckoutManager/V7/CommitOrderProcessor.php';

        $container->privates['pimcore_ecommerce.checkout_manager.default.commit_order_processor'] = $instance = new \Pimcore\Bundle\EcommerceFrameworkBundle\CheckoutManager\V7\CommitOrderProcessor(($container->services['Symfony\\Component\\Lock\\LockFactory'] ?? $container->getLockFactoryService()), ($container->privates['Pimcore\\Bundle\\EcommerceFrameworkBundle\\OrderManager\\OrderManagerLocatorInterface'] ?? $container->load('getOrderManagerLocatorInterfaceService')), ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()), ($container->services['Pimcore\\Log\\ApplicationLogger'] ?? $container->load('getApplicationLoggerService')), []);

        $a = ($container->services['monolog.logger.pimcore_ecommerce'] ?? $container->load('getMonolog_Logger_PimcoreEcommerceService'));

        $instance->setLogger($a);
        $instance->setLogger($a);

        return $instance;
    }
}
