<?php

namespace ContainerOFu2wWx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Firewall_Map_Context_DemoFrontendService extends App_KernelProdContainer
{
    /*
     * Gets the private 'security.firewall.map.context.demo_frontend' shared service.
     *
     * @return \Symfony\Bundle\SecurityBundle\Security\FirewallContext
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-bundle/Security/FirewallContext.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Util/TargetPathTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Firewall/ExceptionListener.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/EntryPoint/AuthenticationEntryPointInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/hwi/oauth-bundle/Security/Http/EntryPoint/OAuthEntryPoint.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Firewall/FirewallListenerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Firewall/AbstractListener.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/Firewall/LogoutListener.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-bundle/Security/FirewallConfig.php';

        $a = ($container->services['.container.private.security.token_storage'] ?? $container->get_Container_Private_Security_TokenStorageService());
        $b = ($container->privates['security.http_utils'] ?? $container->getSecurity_HttpUtilsService());

        return $container->privates['security.firewall.map.context.demo_frontend'] = new \Symfony\Bundle\SecurityBundle\Security\FirewallContext(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['security.channel_listener'] ?? $container->load('getSecurity_ChannelListenerService'));
            yield 1 => ($container->privates['security.context_listener.1'] ?? $container->load('getSecurity_ContextListener_1Service'));
            yield 2 => ($container->privates['security.authentication.listener.form.demo_frontend'] ?? $container->load('getSecurity_Authentication_Listener_Form_DemoFrontendService'));
            yield 3 => ($container->privates['hwi_oauth.authentication.listener.oauth.demo_frontend'] ?? $container->load('getHwiOauth_Authentication_Listener_Oauth_DemoFrontendService'));
            yield 4 => ($container->privates['security.authentication.listener.rememberme.demo_frontend'] ?? $container->load('getSecurity_Authentication_Listener_Rememberme_DemoFrontendService'));
            yield 5 => ($container->privates['security.authentication.listener.anonymous.demo_frontend'] ?? $container->load('getSecurity_Authentication_Listener_Anonymous_DemoFrontendService'));
            yield 6 => ($container->privates['security.access_listener'] ?? $container->load('getSecurity_AccessListenerService'));
        }, 7), new \Symfony\Component\Security\Http\Firewall\ExceptionListener($a, ($container->privates['scheb_two_factor.security.authentication.trust_resolver'] ?? $container->getSchebTwoFactor_Security_Authentication_TrustResolverService()), $b, 'demo_frontend', new \HWI\Bundle\OAuthBundle\Security\Http\EntryPoint\OAuthEntryPoint(($container->services['http_kernel'] ?? $container->getHttpKernelService()), $b, 'account-login', false), NULL, NULL, ($container->services['monolog.logger.security'] ?? $container->getMonolog_Logger_SecurityService()), false), new \Symfony\Component\Security\Http\Firewall\LogoutListener($a, $b, ($container->privates['security.event_dispatcher.demo_frontend'] ?? $container->load('getSecurity_EventDispatcher_DemoFrontendService')), ['csrf_parameter' => '_csrf_token', 'csrf_token_id' => 'logout', 'logout_path' => 'account-logout']), new \Symfony\Bundle\SecurityBundle\Security\FirewallConfig('demo_frontend', 'security.user_checker', NULL, true, false, 'cmf.security.user_provider.oauth', 'demo_frontend', 'hwi_oauth.authentication.entry_point.oauth.demo_frontend', NULL, NULL, [0 => 'form_login', 1 => 'oauth', 2 => 'remember_me', 3 => 'anonymous'], NULL));
    }
}
