<?php

namespace ContainerOFu2wWx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSegmentTrackerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'CustomerManagementFrameworkBundle\Targeting\SegmentTracker' shared autowired service.
     *
     * @return \CustomerManagementFrameworkBundle\Targeting\SegmentTracker
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pimcore/customer-management-framework-bundle/src/Targeting/SegmentTracker.php';

        return $container->privates['CustomerManagementFrameworkBundle\\Targeting\\SegmentTracker'] = new \CustomerManagementFrameworkBundle\Targeting\SegmentTracker(($container->privates['Pimcore\\Targeting\\Storage\\CookieStorage'] ?? $container->getCookieStorageService()), ($container->privates['Pimcore\\Targeting\\DataLoader'] ?? $container->getDataLoaderService()), ($container->services['CustomerManagementFrameworkBundle\\SegmentManager\\SegmentManagerInterface'] ?? $container->getSegmentManagerInterfaceService()), ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()));
    }
}
