<?php

namespace ContainerOFu2wWx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Authentication_Provider_Dao_DemoFrontend_TwoFactorDecorator_InnerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'security.authentication.provider.dao.demo_frontend.two_factor_decorator.inner' shared service.
     *
     * @return \Symfony\Component\Security\Core\Authentication\Provider\DaoAuthenticationProvider
     *
     * @deprecated Since symfony/security-bundle 5.3: The "security.authentication.provider.dao.demo_frontend.two_factor_decorator.inner" service is deprecated, use the new authenticator system instead.
     */
    public static function do($container, $lazyLoad = true)
    {
        trigger_deprecation('symfony/security-bundle', '5.3', 'The "security.authentication.provider.dao.demo_frontend.two_factor_decorator.inner" service is deprecated, use the new authenticator system instead.');

        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/User/UserCheckerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/User/InMemoryUserChecker.php';

        return new \Symfony\Component\Security\Core\Authentication\Provider\DaoAuthenticationProvider(($container->privates['cmf.security.user_provider.oauth'] ?? $container->load('getCmf_Security_UserProvider_OauthService')), ($container->services['hwi_oauth.user_checker'] ?? ($container->services['hwi_oauth.user_checker'] = new \Symfony\Component\Security\Core\User\InMemoryUserChecker())), 'demo_frontend', ($container->privates['pimcore.security.encoder_factory'] ?? $container->load('getPimcore_Security_EncoderFactoryService')), true);
    }
}
