<?php

namespace ContainerOFu2wWx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Authentication_Provider_Rememberme_DemoFrontend_TwoFactorDecorator_InnerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'security.authentication.provider.rememberme.demo_frontend.two_factor_decorator.inner' shared service.
     *
     * @return \Symfony\Component\Security\Core\Authentication\Provider\RememberMeAuthenticationProvider
     *
     * @deprecated Since symfony/security-bundle 5.3: The "security.authentication.provider.rememberme.demo_frontend.two_factor_decorator.inner" service is deprecated, use the new authenticator system instead.
     */
    public static function do($container, $lazyLoad = true)
    {
        trigger_deprecation('symfony/security-bundle', '5.3', 'The "security.authentication.provider.rememberme.demo_frontend.two_factor_decorator.inner" service is deprecated, use the new authenticator system instead.');

        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/User/UserCheckerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/User/InMemoryUserChecker.php';

        return new \Symfony\Component\Security\Core\Authentication\Provider\RememberMeAuthenticationProvider(($container->services['hwi_oauth.user_checker'] ?? ($container->services['hwi_oauth.user_checker'] = new \Symfony\Component\Security\Core\User\InMemoryUserChecker())), 'mOh6536xDgPgqzIaQ1/Hp4l5JwAkZkXPXxfC5uE9Nbw=', 'demo_frontend');
    }
}
