<?php

namespace ContainerOFu2wWx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTemplateExporterService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.mvOr3_S.CustomerManagementFrameworkBundle\Newsletter\ProviderHandler\Mailchimp\TemplateExporter' shared service.
     *
     * @return \CustomerManagementFrameworkBundle\Newsletter\ProviderHandler\Mailchimp\TemplateExporter
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.mvOr3_S": it references class "CustomerManagementFrameworkBundle\\Newsletter\\ProviderHandler\\Mailchimp\\TemplateExporter" but no such service exists.');
    }
}
