<?php

use Twig\Environment;
use Twig\Error\LoaderError;
use Twig\Error\RuntimeError;
use Twig\Extension\SandboxExtension;
use Twig\Markup;
use Twig\Sandbox\SecurityError;
use Twig\Sandbox\SecurityNotAllowedTagError;
use Twig\Sandbox\SecurityNotAllowedFilterError;
use Twig\Sandbox\SecurityNotAllowedFunctionError;
use Twig\Source;
use Twig\Template;

/* areas/wysiwyg/view.html.twig */
class __TwigTemplate_d1bd6cfab40a8265b36e102ecee075610ffb0ad3acfbfdf4da356af5f2b3cef8 extends Template
{
    private $source;
    private $macros = [];

    public function __construct(Environment $env)
    {
        parent::__construct($env);

        $this->source = $this->getSourceContext();

        $this->parent = false;

        $this->blocks = [
        ];
    }

    protected function doDisplay(array $context, array $blocks = [])
    {
        $macros = $this->macros;
        $__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e = $this->extensions["Symfony\\Bundle\\WebProfilerBundle\\Twig\\WebProfilerExtension"];
        $__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e->enter($__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e_prof = new \Twig\Profiler\Profile($this->getTemplateName(), "template", "areas/wysiwyg/view.html.twig"));

        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02 = $this->extensions["Symfony\\Bridge\\Twig\\Extension\\ProfilerExtension"];
        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02->enter($__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02_prof = new \Twig\Profiler\Profile($this->getTemplateName(), "template", "areas/wysiwyg/view.html.twig"));

        // line 1
        $context["content"] = $this->extensions['Pimcore\Twig\Extension\DocumentEditableExtension']->renderEditable($context, "wysiwyg", "content");
        // line 2
        echo "
";
        // line 4
        if (twig_test_empty(twig_get_attribute($this->env, $this->source, (isset($context["document"]) || array_key_exists("document", $context) ? $context["document"] : (function () { throw new RuntimeError('Variable "document" does not exist.', 4, $this->source); })()), "getDescription", [], "method", false, false, false, 4))) {
            // line 5
            echo "    ";
            twig_get_attribute($this->env, $this->source, call_user_func_array($this->env->getFunction('pimcore_head_meta')->getCallable(), []), "setDescription", [0 => twig_get_attribute($this->env, $this->source, (isset($context["content"]) || array_key_exists("content", $context) ? $context["content"] : (function () { throw new RuntimeError('Variable "content" does not exist.', 5, $this->source); })()), "getData", [], "method", false, false, false, 5), 1 => 160], "method", false, false, false, 5);
        }
        // line 7
        echo "
<section class=\"area-wysiwyg\">
    ";
        // line 9
        $this->env->getExtension('Pimcore\Twig\Extension\GlossaryExtension')->start();
        // line 10
        echo "        ";
        echo (isset($context["content"]) || array_key_exists("content", $context) ? $context["content"] : (function () { throw new RuntimeError('Variable "content" does not exist.', 10, $this->source); })());
        echo "
    ";

        $this->env->getExtension('Pimcore\Twig\Extension\GlossaryExtension')->stop();
        // line 12
        echo "</section>
";
        
        $__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e->leave($__internal_085b0142806202599c7fe3b329164a92397d8978207a37e79d70b8c52599e33e_prof);

        
        $__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02->leave($__internal_319393461309892924ff6e74d6d6e64287df64b63545b994e100d4ab223aed02_prof);

    }

    public function getTemplateName()
    {
        return "areas/wysiwyg/view.html.twig";
    }

    public function isTraitable()
    {
        return false;
    }

    public function getDebugInfo()
    {
        return array (  67 => 12,  60 => 10,  58 => 9,  54 => 7,  50 => 5,  48 => 4,  45 => 2,  43 => 1,);
    }

    public function getSourceContext()
    {
        return new Source("{% set content = pimcore_wysiwyg('content') %}

{# add autogenerated meta description #}
{% if document.getDescription() is empty %}
    {% do pimcore_head_meta().setDescription(content.getData(), 160) %}
{% endif %}

<section class=\"area-wysiwyg\">
    {% pimcoreglossary %}
        {{ content|raw }}
    {% endpimcoreglossary %}
</section>
", "areas/wysiwyg/view.html.twig", "/opt/bitnami/pimcore/templates/areas/wysiwyg/view.html.twig");
    }
}
