<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOFu2wWx\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOFu2wWx/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerOFu2wWx.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerOFu2wWx\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerOFu2wWx\App_KernelProdContainer([
    'container.build_hash' => 'OFu2wWx',
    'container.build_id' => '4dad229d',
    'container.build_time' => 1639233142,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOFu2wWx');
