<?php

namespace ContainerCcF9MAJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UOQLfi6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UOQLfi6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UOQLfi6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'customerView' => ['services', 'CustomerManagementFrameworkBundle\\CustomerView\\CustomerViewInterface', 'getCustomerViewInterfaceService', false],
        ], [
            'customerView' => 'CustomerManagementFrameworkBundle\\CustomerView\\CustomerViewInterface',
        ]);
    }
}
