<?php

namespace ContainerCcF9MAJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QS8wkh2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QS8wkh2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QS8wkh2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'localeService' => ['services', 'Pimcore\\Localization\\LocaleServiceInterface', 'getLocaleServiceInterfaceService', false],
            'modelFactory' => ['services', 'pimcore.model.factory', 'getPimcore_Model_FactoryService', false],
            'service' => ['services', 'Pimcore\\Bundle\\DataHubBundle\\GraphQL\\Service', 'getService2Service', true],
        ], [
            'localeService' => 'Pimcore\\Localization\\LocaleServiceInterface',
            'modelFactory' => '?',
            'service' => 'Pimcore\\Bundle\\DataHubBundle\\GraphQL\\Service',
        ]);
    }
}
