<?php

namespace ContainerCcF9MAJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_J2tQc0TService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.J2tQc0T' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.J2tQc0T'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'segmentManager' => ['services', 'CustomerManagementFrameworkBundle\\SegmentManager\\SegmentManagerInterface', 'getSegmentManagerInterfaceService', false],
        ], [
            'segmentManager' => 'CustomerManagementFrameworkBundle\\SegmentManager\\SegmentManagerInterface',
        ]);
    }
}
