<?php

namespace ContainerCcF9MAJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8Iopj6dService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8Iopj6d' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8Iopj6d'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'routingService' => ['services', 'router', 'getRouterService', false],
            'service' => ['services', 'Pimcore\\Bundle\\DataHubBundle\\GraphQL\\Service', 'getService2Service', true],
        ], [
            'routingService' => '?',
            'service' => 'Pimcore\\Bundle\\DataHubBundle\\GraphQL\\Service',
        ]);
    }
}
