<?php

namespace ContainerCcF9MAJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCmf_ActionTrigger_QueueService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'cmf.action_trigger.queue' shared autowired service.
     *
     * @return \CustomerManagementFrameworkBundle\ActionTrigger\Queue\DefaultQueue
     *
     * @deprecated The "cmf.action_trigger.queue" service is deprecated. Use "CustomerManagementFrameworkBundle\ActionTrigger\Queue\QueueInterface" instead
     */
    public static function do($container, $lazyLoad = true)
    {
        trigger_deprecation('', '', 'The "cmf.action_trigger.queue" service is deprecated. Use "CustomerManagementFrameworkBundle\\ActionTrigger\\Queue\\QueueInterface" instead');

        return $container->services['cmf.action_trigger.queue'] = new \CustomerManagementFrameworkBundle\ActionTrigger\Queue\DefaultQueue();
    }
}
