<?php

namespace ContainerCcF9MAJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCmf_Linkactivitydefinition_LinkgeneratorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'cmf.link-activity-definition.linkgenerator' shared autowired service.
     *
     * @return \CustomerManagementFrameworkBundle\LinkGenerator\LinkActivityDefinitionLinkGenerator
     *
     * @deprecated The "cmf.link-activity-definition.linkgenerator" service is deprecated. Use "CustomerManagementFrameworkBundle\LinkGenerator\LinkActivityDefinitionLinkGenerator" instead
     */
    public static function do($container, $lazyLoad = true)
    {
        trigger_deprecation('', '', 'The "cmf.link-activity-definition.linkgenerator" service is deprecated. Use "CustomerManagementFrameworkBundle\\LinkGenerator\\LinkActivityDefinitionLinkGenerator" instead');

        return $container->services['cmf.link-activity-definition.linkgenerator'] = new \CustomerManagementFrameworkBundle\LinkGenerator\LinkActivityDefinitionLinkGenerator('*|ID_ENCODED|*');
    }
}
