<?php

namespace ContainerCcF9MAJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCmf_CustomerExporterManagerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'cmf.customer_exporter_manager' shared autowired service.
     *
     * @return \CustomerManagementFrameworkBundle\CustomerList\ExporterManager
     *
     * @deprecated The "cmf.customer_exporter_manager" service is deprecated. Use "CustomerManagementFrameworkBundle\CustomerList\ExporterManagerInterface" instead
     */
    public static function do($container, $lazyLoad = true)
    {
        trigger_deprecation('', '', 'The "cmf.customer_exporter_manager" service is deprecated. Use "CustomerManagementFrameworkBundle\\CustomerList\\ExporterManagerInterface" instead');

        return $container->services['cmf.customer_exporter_manager'] = new \CustomerManagementFrameworkBundle\CustomerList\ExporterManager($container->parameters['pimcore_customer_management_framework.customer_list.exporters']);
    }
}
