<?php

namespace ContainerCcF9MAJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessenger_Bus_Default_Middleware_HandleMessageService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'messenger.bus.default.middleware.handle_message' shared service.
     *
     * @return \Symfony\Component\Messenger\Middleware\HandleMessageMiddleware
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Middleware/MiddlewareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlersLocatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlersLocator.php';

        $container->privates['messenger.bus.default.middleware.handle_message'] = $instance = new \Symfony\Component\Messenger\Middleware\HandleMessageMiddleware(new \Symfony\Component\Messenger\Handler\HandlersLocator(['Symfony\\Component\\Mailer\\Messenger\\SendEmailMessage' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.tGvt0LH'] ?? $container->load('get_Messenger_HandlerDescriptor_TGvt0LHService'));
        }, 1), 'Symfony\\Component\\Notifier\\Message\\ChatMessage' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.vMw0m61'] ?? $container->load('get_Messenger_HandlerDescriptor_VMw0m61Service'));
        }, 1), 'Symfony\\Component\\Notifier\\Message\\SmsMessage' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.XZowc.T'] ?? $container->load('get_Messenger_HandlerDescriptor_XZowc_TService'));
        }, 1), 'Symfony\\Component\\Notifier\\Message\\PushMessage' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.Lml2ICs'] ?? $container->load('get_Messenger_HandlerDescriptor_Lml2ICsService'));
        }, 1), 'Presta\\SitemapBundle\\Messenger\\DumpSitemapMessage' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.axmPPI9'] ?? $container->load('get_Messenger_HandlerDescriptor_AxmPPI9Service'));
        }, 1), 'Pimcore\\Messenger\\SendNewsletterMessage' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.lXCgBJt'] ?? $container->load('get_Messenger_HandlerDescriptor_LXCgBJtService'));
        }, 1), 'Pimcore\\Messenger\\VideoConvertMessage' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.zPF.n3v'] ?? $container->load('get_Messenger_HandlerDescriptor_ZPF_N3vService'));
        }, 1), 'Pimcore\\Messenger\\CleanupThumbnailsMessage' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.M549gSF'] ?? $container->load('get_Messenger_HandlerDescriptor_M549gSFService'));
        }, 1), 'Pimcore\\Messenger\\AssetUpdateTasksMessage' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.4dW7fbT'] ?? $container->load('get_Messenger_HandlerDescriptor_4dW7fbTService'));
        }, 1), 'Pimcore\\Messenger\\MaintenanceTaskMessage' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.TbhewNb'] ?? $container->load('get_Messenger_HandlerDescriptor_TbhewNbService'));
        }, 1), 'Pimcore\\Messenger\\SearchBackendMessage' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.ZD5jppI'] ?? $container->load('get_Messenger_HandlerDescriptor_ZD5jppIService'));
        }, 1), 'Pimcore\\Messenger\\OptimizeImageMessage' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.aou1rPk'] ?? $container->load('get_Messenger_HandlerDescriptor_Aou1rPkService'));
        }, 1), 'Pimcore\\Messenger\\GenerateWeb2PrintPdfMessage' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.A03hLpI'] ?? $container->load('get_Messenger_HandlerDescriptor_A03hLpIService'));
        }, 1), 'Pimcore\\Messenger\\VersionDeleteMessage' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.arnT_jz'] ?? $container->load('get_Messenger_HandlerDescriptor_ArnTJzService'));
        }, 1), 'Pimcore\\Messenger\\SanityCheckMessage' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.mm6wD37'] ?? $container->load('get_Messenger_HandlerDescriptor_Mm6wD37Service'));
        }, 1)]));

        if ($container->has('monolog.logger.messenger')) {
            $instance->setLogger(($container->services['monolog.logger.messenger'] ?? $container->load('getMonolog_Logger_MessengerService')));
        }

        return $instance;
    }
}
